export interface GuideField {
  flag: string;
  label: string;
  choices?: readonly string[];
  optional?: boolean;
  multiple?: boolean;
  defaultValue?: string;
}
export interface CommandAction { label: string; command: string[]; fields: GuideField[]; mutates: boolean; }
const field = (flag: string, label: string): GuideField => ({ flag, label });
const version = field("--version", "Artifact version");
const artifact = field("--artifact", "Artifact ID");
const assetIds: GuideField = { flag: "--asset", label: "Asset IDs (comma separated; blank for none)", optional: true, multiple: true };
export const commandActions: Record<string, CommandAction> = {
  revise: { label: "Revise document", command: ["artifact", "revise"], mutates: true, fields: [field("--id", "Artifact ID"), version, field("--path", "New project-relative file path"), field("--rationale", "Revision rationale"), assetIds] },
  submit: { label: "Submit for review", command: ["artifact", "submit"], mutates: true, fields: [field("--id", "Artifact ID"), version] },
  review: { label: "Record review", command: ["review"], mutates: true, fields: [artifact, version, { flag: "--tier", label: "Review tier", choices: ["self", "peer", "creative-lead", "stakeholder"] }, { flag: "--decision", label: "Explicit decision", choices: ["approved", "approved-with-conditions", "returned"] }, field("--reviewer", "Reviewer name"), { flag: "--reviewer-id", label: "Registered reviewer participant ID (if applicable)", optional: true }, field("--reason", "Review reason") ] },
  participant: { label: "Add participant", command: ["participant", "add"], mutates: true, fields: [field("--id", "Participant ID"), field("--name", "Participant name"), { flag: "--role", label: "Role", choices: ["creative-lead", "stakeholder", "developer", "peer"] }] },
  owner: { label: "Assign decision owner", command: ["participant", "own"], mutates: true, fields: [{ flag: "--area", label: "Decision area", choices: ["creative-direction", "business-direction", "implementation-readiness"] }, field("--participant", "Registered participant ID")] },
  asset: { label: "Add asset", command: ["asset", "add"], mutates: true, fields: [field("--id", "Asset ID"), field("--title", "Title"), {flag:"--creator",label:"Creator (if known)",optional:true}, field("--source", "Source and attribution"), {flag:"--owner",label:"Creative owner participant ID (if applicable)",optional:true}, field("--role", "Intended visual role"), { flag: "--modification", label: "Modification permission", choices: ["locked", "adaptable", "inspiration-only"] }, { flag: "--rights", label: "Documented rights", choices: ["unknown", "cleared", "restricted"], defaultValue: "unknown" }, field("--path", "Source path (unknown rights) or project-relative managed path"), {flag: "--provider", label: "Allowed providers (comma separated)", multiple:true, defaultValue: "local-html-svg" }, {flag:"--allow",label:"Allowed treatments (comma separated)",multiple:true,optional:true}, {flag:"--prohibit",label:"Prohibited treatments (comma separated)",multiple:true,optional:true}, field("--responsive", "Responsive guidance"), field("--accessibility", "Accessibility intent")] },
  "asset-update": { label: "Update asset rights or storage", command: ["asset", "update"], mutates:true, fields: [field("--id", "Asset ID"), {flag:"--rights",label:"Updated documented rights",choices:["unknown","cleared","restricted"],optional:true}, {flag:"--path",label:"Managed project-relative path (required when clearing private storage)",optional:true}, {flag:"--provider",label:"Updated providers (comma separated; blank leaves unchanged)",multiple:true,optional:true}] },
  feedback: { label: "Import feedback", command: ["feedback", "import"], mutates:true, fields: [field("--id", "Feedback ID"), field("--file", "Text file containing original feedback"), field("--source", "Feedback source"), {flag:"--class",label:"Classifications (comma separated)",multiple:true}, field("--interpretation", "Your separate interpretation"), {flag:"--author",label:"Author (if known)",optional:true}, {flag:"--target-kind",label:"Target kind",choices:["project","asset","artifact"],optional:true}, {flag:"--target-id",label:"Target ID (when kind is supplied)",optional:true}, {flag:"--target-version",label:"Target artifact version (optional)",optional:true}] },
  "feedback-resolve": { label: "Resolve feedback", command: ["feedback", "resolve"], mutates:true, fields: [field("--id", "Feedback ID"),field("--resolution", "Responsible teammate's resolution"),{flag:"--artifact",label:"Resulting artifact IDs (comma separated)",multiple:true,optional:true}] },
  reference: { label: "Add reference", command: ["reference", "add"], mutates:true, fields: [field("--id","Reference ID"),field("--url","Source URL"),field("--title","Title"),field("--relevance","Relevance"),field("--lesson","Lesson"),field("--avoid-copying","What must not be copied"),field("--attribution","Attribution"),{flag:"--license-status",label:"License status",choices:["unknown","verified","not-applicable"],defaultValue:"unknown"},field("--license-notes","License notes")] },
  study: { label: "Create private study", command: ["explore-private"], mutates:true, fields: [field("--id","Study ID"),field("--title","Title"),field("--question","Creative question"),field("--rationale","Rationale"),{...assetIds,optional:false},{flag:"--assumption",label:"Assumptions (comma separated)",multiple:true,optional:true},{flag:"--note",label:"Composition notes (comma separated)",multiple:true,optional:true}] },
  promote: { label: "Promote study", command: ["promote"], mutates:true, fields: [artifact,version,field("--path","Existing project-visible review file path"),field("--rationale","Promotion rationale")] },
  advance: { label: "Advance stage", command: ["stage", "advance"], mutates:true, fields: [{flag:"--to",label:"Next stage",choices:["research","territories","visual-language","exploration","review","handoff"]}] },
  validate: { label: "Validate project", command: ["validate"], mutates:false, fields: [] },
  context: { label: "Render agent context", command: ["context"], mutates:false, fields: [{flag:"--host",label:"Host",choices:["codex","claude"]}] }
};
